import string
import secrets
import random

def random_pass():
    n = 10
    res = ''.join(secrets.choice(string.ascii_uppercase + string.digits + string.ascii_lowercase) for i in range(n))
    print(f'The password autogenerated for user safety is, {res}')


def usr_pass(word, num, spec):
    vow = {'a', 'e', 'i', 'o', 'u'}
    new_word = set(word)
    n = len(word)    
    check_vow = new_word.intersection(vow)
    if check_vow == set():
        j = random.randint(0, n-1)
        lst_word = list(word)
        lst_word[j] = lst_word[j].upper()
        word = ''.join(lst_word)
    else:
        lst_word = list(word)
        n = len(lst_word)
        check_vow = list(check_vow)
        for i in range(0, n):
            for j in range(0, len(check_vow)):
                if lst_word[i] == check_vow[j]:
                    lst_word[i] = lst_word[i].upper()
        word=''.join(lst_word)
        
    print(f'The strong password generated for user safety based on user input is, {spec}{word}{num}')
        
welcome = input("Hey welcome, How do u want to generate your password ? if u want to give inputs and generate enter 'u' or if u want the computer to randomly generate enter 'r'").lower()
if (welcome == 'u'):
    word =input('Enter a word you want in the password : ').lower()
    num = int(input("Enter a number you want in the password : "))
    spec = input("Enter a special character you want in your password(example : #,$,%) : ")
    usr_pass(word,num, spec)

else:
    random_pass()



    
